name: Manga Auto Cleaner Engine

on:
  push:
    paths:
      - 'raw_img/**'

jobs:
  clean-manga:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Cleaner Engine
      run: python cleaner.py

    - name: Commit and Push Cleaned Images
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Zizo-Auto-Cleaner"
        git add clean_img/*
        # إذا ماكو شي جديد يوقف السيرفر بدون كراش
        git diff-index --quiet HEAD || git commit -m "🧼 تم تبييض الفصل بنجاح ساحق!"
        # 🛠️ الضربة القاضية: الدفع بالقوة وعبر الـ Token الافتراضي للسيرفر
        git push origin main --force


