name: Manga Auto Cleaner Engine with MangaScourX

on:
  push:
    paths:
      - 'raw_img/**'

jobs:
  clean-manga:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # تفعيل الكاش لتسريع تحميل الموديلات بـ EasyOCR

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Install Core Library Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MangaScourX Cleaner Engine
      run: python cleaner.py

    - name: Commit and Push Cleaned Images
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Zizo-Auto-Cleaner"
        git add clean_img/*
        git diff-index --quiet HEAD || git commit -m "🧼 تم التبييض والتنظيف الاحترافي بواسطة وحش MangaScourX محلياً!"
        git push origin main
        git push origin main --force
        git push origin main --force


